- name: Configure EC2 for E-commerce App
  hosts: web
  become: true
 
  tasks:
 
    - name: Update system
      yum:
        name: "*"
        state: latest
 
    - name: Install Docker
      yum:
        name: docker
        state: present
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
 
    - name: Run Nginx web server
      shell: docker run -d -p 80:80 --name ecommerce nginx
      ignore_errors: yes
