name: DevOps CI/CD Pipeline

on:
push:
branches:
- main

jobs:

# =========================

# TERRAFORM

# =========================

terraform:
runs-on: ubuntu-latest

```
defaults:
  run:
    working-directory: terraform

outputs:
  instance_ips: ${{ steps.export.outputs.instance_ips }}

steps:
  # Checkout repository
  - name: Checkout code
    uses: actions/checkout@v4

  # Configure AWS credentials
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws-region: ${{ secrets.AWS_REGION }}

  # Verify AWS authentication
  - name: Test AWS Credentials
    run: aws sts get-caller-identity

  # Install Terraform
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  # Terraform init
  - name: Terraform Init
    run: terraform init

  # Terraform apply
  - name: Terraform Apply
    run: terraform apply -auto-approve

  # Export EC2 public IPs
  - name: Export IPs
    id: export
    run: |
      IPS=$(terraform output -json instance_public_ips | jq -r '.[]' | tr '\n' ',' | sed 's/,$//')
      echo "instance_ips=$IPS" >> $GITHUB_OUTPUT
```

# =========================

# ANSIBLE

# =========================

ansible:
runs-on: ubuntu-latest
needs: terraform

```
steps:
  # Checkout repository
  - name: Checkout code
    uses: actions/checkout@v4

  # Install Ansible
  - name: Install Ansible
    run: |
      sudo apt update
      sudo apt install -y ansible jq

  # Configure SSH key
  - name: Setup SSH Key
    run: |
      echo "${{ secrets.EC2_KEY }}" > key.pem
      chmod 600 key.pem

  # Generate inventory
  - name: Generate Inventory
    run: |
      echo "[web]" > inventory.ini

      for ip in $(echo "${{ needs.terraform.outputs.instance_ips }}" | tr ',' ' ')
      do
        echo "$ip ansible_user=ec2-user ansible_ssh_private_key_file=key.pem" >> inventory.ini
      done

      cat inventory.ini

  # Wait for EC2 instances
  - name: Wait for SSH
    run: |
      sleep 60

  # Run Ansible playbook
  - name: Run Ansible
    run: |
      ansible-playbook -i inventory.ini ansible/deploy.yml
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
```
